# permissions for end users to edit sampleoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleoperator-editor-role
rules:
- apiGroups:
  - sample-operator.example.com
  resources:
  - sampleoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample-operator.example.com
  resources:
  - sampleoperators/status
  verbs:
  - get
