# permissions for end users to view sampleoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleoperator-viewer-role
rules:
- apiGroups:
  - sample-operator.example.com
  resources:
  - sampleoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample-operator.example.com
  resources:
  - sampleoperators/status
  verbs:
  - get
